# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install -qqq -r requirements.txt
  - pip3 install -qqq http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl

# command to run tests, e.g. python setup.py test
script:
    - PYTHONPATH=$PTYHONPATH:$PWD py.test

# matrix:
#   include:
#     - env: LINT_CHECK
#       python: "3.5"
#       install: pip install flake8
#       script: flake8
